sampling_friction_coef: 0.8
num_cone_faces: 8
grasp_samples_per_surface_point: 4
min_num_grasps: 100
target_num_grasps: 200
num_grasp_rots: 8
max_num_surface_points: 100
grasp_dist_thresh: 0
gripper_max_width: 0.05
max_sampling_iteration: 300