# ---------------------------------------------------------
# 파지점 계산 파라미터들
# ---------------------------------------------------------
sampling_friction_coef: 0.4
num_cone_faces: 8
grasp_samples_per_surface_point: 4
min_num_grasps: 100
target_num_grasps: 200
num_grasp_rots: 8
max_num_surface_points: 100
grasp_dist_thresh: 0
gripper_max_width: 0.05
max_sampling_iteration: 300

# ---------------------------------------------------------
# 그리퍼 정보
# ---------------------------------------------------------
hande:
  T_mesh_gripper:
    - [1.0,  0.0,  0.0,  0.0]
    - [0.0,  0.0,  1.0,  0.056]
    - [0.0, -1.0,  0.0,  0.0]
    - [0.0,  0.0,  0.0,  1.0]
  mesh_path: '/home/minsoo/Dexnet_Minsoo/Minsoo_net/data/gripper/gripper.stl'
  
# ---------------------------------------------------------
# 불확실성(Uncertainty) 모델링을 위한 Gaussian 노이즈 설정값
# 단위: 미터(m), 라디안(rad), 스케일 비율 등
# ---------------------------------------------------------

# 1. 객체 및 그리퍼 위치/회전 노이즈 (Translation & Rotation)
# 위치 노이즈 (예: 0.005 = 5mm의 위치 오차)
sigma_translation: 0.005

# 회전 노이즈 (예: 0.05 = 약 2.8도의 각도 오차)
sigma_rotation: 0.05

sigma_gripper_translation: 0.005

# 회전 노이즈 (예: 0.05 = 약 2.8도의 각도 오차)
sigma_gripper_rotation: 0.05

# 2. 객체 고유 속성 노이즈 (Object Pose RV)
# 크기(Scale) 노이즈 (예: 0.01 = 1%의 크기 오차)
sigma_scale: 0.03

# 무게중심(Center of Mass) 노이즈 (예: 0.002 = 2mm의 무게중심 오차)
sigma_center_of_mass: 0.002

# 3. 그리퍼 고유 속성 노이즈 (Grasp Pose RV)
# 그리퍼 접근 각도(Approach Angle) 노이즈 (예: 0.05 = 약 2.8도의 접근 각도 오차)
sigma_gripper_approach_angle: 0.05

# 4. 물리/환경 파라미터 노이즈 (Params RV)
# 표면 마찰 계수(Friction Coefficient) 노이즈
sigma_friction: 0.1
mean_friction: 0.4

# 5. 시뮬레이션 랜더링 관련 물리값들
sigma_matalic : 0.1
mean_matalic: 0.9
min_matalic :  0.8
max_matalic : 1.0

mean_roughness : 0.40
min_roughness : 0.10
sigma_roughness: 0.1
max_roughness : 0.60 

# ---------------------------------------------------------
# 카메라 파라미터들
# ---------------------------------------------------------
block_height: 7
uniqueness_ratio: 50


# ---------------------------------------------------------
# 데이터셋 생성 파라미터들
# ---------------------------------------------------------
zarr_path : "grasp_dataset_0408.zarr"
num_grasps : 300
quality_threshold : 0.002
stable_pose_prob_threshold : 0.012
num_stable_poses : 6 
max_angle_deg : 20
cam_offset_min : 0.30
cam_offset_max : 0.40
cam_offset_step : 10

# ---------------------------------------------------------
# 학습 파라미터
# ---------------------------------------------------------
#zarr path, quality threshold = 터미널에서 입력받음.