tilts:
  left:
    joint_1: 16.00
    joint_2: -6.0000
    joint_3: 107.0000
    joint_4: -11.0002
    joint_5: 51.0004
    joint_6: -67.9872

  vertical:
    joint_1: 9.0
    joint_2: 17.0
    joint_3: 66.0
    joint_4: 0.0
    joint_5: 95.0
    joint_6: -77.0

  back:
    joint_1: 25.0007
    joint_2: 31.9978
    joint_3: 45.0018
    joint_4: -21.0000
    joint_5: 112.9928
    joint_6: -61.9999
  
  

cem_num: 5 # CEM 최대 반복 횟수
hard_offset: -0.01 # Realsense 카메라 자체 오차

max_edge: 1000 # Online sampling 선택 edge points 개수
image_margin: 0.25 # 이미지 가장자리 처리
max_grasps: 100 # Online sampling 최종 선택 grasps 개수
gripper_width: 0.05 # 그리퍼 폭
finger_length: 0.158
gripper_width_min: 0.0   # Online sampling 후보 최소 너비 (그리퍼 너비 n배)
gripper_width_max: 1.5

box_z: 0.128 # World좌표 기준 box 위치

sampling_offset: [0.006, 0.05, 10]

place: [0.306, 0.048, 0.104]

model_path: '/root/humble/Dexnet_Minsoo/output/06-04_09-41_grasp_dataset_NEAREST_th0.002/best.pt'